logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    com.vaadin.spring.navigator.SpringViewProvider: WARN
    com.vaadin.spring.server.SpringUIProvider: WARN
server:
  servlet:
    session:
      persistent: false
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.yml